### ISSUE TITLE
help wanted: JSONDecodeError

### ISSUE THREAD

**Issue by xhc19930714** [Chenrj233/LMEDR#1]
Hello,  when I trained on personachat and DSTC7 using your provided comman-line, It all showed me the following error. Have you ever met the same situation when training the model? 
![2023-03-22_100027](https://user-images.githubusercontent.com/17611259/226782663-b1796300-abf3-4283-a0e1-4c7bf6de1f7f.png)

**Comment by Chenrj233** [comment]
This is because we have not uploaded the dataset. You could download the dataset according to the 'dataset' in README and place it in the corresponding folder.

**Comment by xhc19930714** [comment]
> This is because we have not uploaded the dataset. You could download the dataset according to the 'dataset' in README and place it in the corresponding folder.

okay, thanks, I have fixed the problem. But there has been another problem. My env is four 3090 with 24GB each. In your paper, the experiment is also conducted using 3090. But when I train the model using train_personaChat.py.  Even I use smalled batch_size,  when the training process is going to finish. It only get the out of memory result. Have you ever met this phenomenon in your experiment?

**Comment by Chenrj233** [comment]
Thank you very much for your feedback. You can try the following script to run on the 3090,
```
python train_PersonaChat.py --lr 8e-6 \
--epochs 20 \
--train_batch_size 2 \
--valid_batch_size 2 \
--infer_batch_size 64 
```
At the same time, we also update the code to better save each checkpoint.

**Comment by xhc19930714** [comment]
> 



> Thank you very much for your feedback. You can try the following script to run on the 3090,
> 
> ```
> python train_PersonaChat.py --lr 8e-6 \
> --epochs 20 \
> --train_batch_size 2 \
> --valid_batch_size 2 \
> --infer_batch_size 64 
> ```
> 
> At the same time, we also update the code to better save each checkpoint.

> Thank you very much for your feedback. You can try the following script to run on the 3090,
> 
> ```
> python train_PersonaChat.py --lr 8e-6 \
> --epochs 20 \
> --train_batch_size 2 \
> --valid_batch_size 2 \
> --infer_batch_size 64 
> ```
> 
> At the same time, we also update the code to better save each checkpoint.

thanks for your reply, I will have  a try.
