### ISSUE TITLE
How to set "top_k, top_p, temperature" when evaluation.

### ISSUE THREAD

**Issue by Ozawa333** [Chenrj233/LMEDR#14]
When I use evaluation_PersonaChat.py to evaluate the results, no matter how I change "top_k, top_p, temperature", the evaluation results will not change. Is this normal or there are other setting methods?
当我使用evaluation_PersonaChat.py来评估结果的时候，无论我如何的更改"top_k, top_p, temperature"，评估的结果不会有任何变化，请问这是正常的还是有其他的设置方法。

**Comment by Chenrj233** [comment]
目前可以尝试一下在`evaluation_PersonaChat.py`的第168-172行的generate函数中设置需要的参数，我们会尽快修复这个错误并更新。

**Comment by Ozawa333** [comment]
感谢您的回复，我尝试调整了168-172行中generate函数（如图）但是评估的结果似乎并无变化
<img width="833" alt="image" src="https://github.com/Chenrj233/LMEDR/assets/46550891/7965df9e-abe1-40a1-a6a8-17ff9d280337">

**Comment by Chenrj233** [comment]
您好，我推测这种情况是没有使用采样的策略而导致得，可以加上``do_sample=True``进行尝试，详细的参数介绍可以参考[GenerationMixin](https://huggingface.co/docs/transformers/v4.32.0/en/main_classes/text_generation#transformers.GenerationMixin.generate)，[GenerationConfig](https://huggingface.co/docs/transformers/v4.32.0/en/main_classes/text_generation#transformers.GenerationConfig)希望能够帮助到您。

**Comment by Ozawa333** [comment]
加上do_sample=True后的输出确实产生了变化，但是结果似乎更糟了。请问SOTA结果是在do_sample=False的时候不使用任何decoding strategies 时生成的对吧？
<img width="637" alt="image" src="https://github.com/Chenrj233/LMEDR/assets/46550891/c263816c-5b7c-4055-a955-aae40c21078b">

**Comment by Chenrj233** [comment]
您好，我们的结果是使用beam search的策略进行生成的，没有使用其他的采样策略。

**Comment by Ozawa333** [comment]
好的了解了，感谢您的回复
