### ISSUE TITLE
What is mean of " the corresponding files in /other/"

### ISSUE THREAD

**Issue by LTC232** [Chenrj233/LMEDR#2]
hi,i have some questions about how to find documents named "other".Because i have  installed ParlAI,but i can't find the  documens named "other",just got 'ParlAI/projects/convai2/baselines'

**Comment by Chenrj233** [comment]
That  is, the files `ParlAI/projects/convai2/eval_f1.py` and `ParlAI/projects/convai2/eval_hits.py` should be replaced by `other/eval_f1.py` and `other/eval_hits.py` which we provide in this repository.

**Comment by LTC232** [comment]
ok,thank you!
