### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type

### ISSUE THREAD

**Issue by bizli0618** [Chenrj233/LMEDR#8]
While I was trying to execute the evaluation code, 
python train_PersonaChat.py --load_from persona_original --eval
This error happened.

**Current run is terminating due to exception: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward
Engine run is terminating due to exception: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward**
First picture is about details, and the second one is about where I put the data. 
Does there any mistakes in saving data?
![type_error](https://github.com/Chenrj233/LMEDR/assets/63985988/a9852511-898c-4e3d-a64c-9b160eb8dad9)
![file_directory](https://github.com/Chenrj233/LMEDR/assets/63985988/101d36d1-f5b6-4893-9655-6a8bcf8145a0)

**Comment by Chenrj233** [comment]
You could try to replace the [this line](https://github.com/Chenrj233/LMEDR/blob/b0db3d3d788c1a0207c56e7b869f69ea2dfef084/train_PersonaChat.py#LL280C10-L280C10) with the followering code ```return (tmp_lmlogits, cls_logits), (lmlabels.long(), clslabel)```

**Comment by Chenrj233** [comment]
You can try to replace [this line](https://github.com/Chenrj233/LMEDR/blob/b0db3d3d788c1a0207c56e7b869f69ea2dfef084/train_PersonaChat.py#LL280C10-L280C10) with the followering code ```return (tmp_lmlogits, cls_logits), (lmlabels.long(), clslabel)```

**Comment by bizli0618** [comment]
Thank you for the comment. It works well.
