### ISSUE TITLE
Fine Tuning model

### ISSUE THREAD

**Issue by bizli0618** [Chenrj233/LMEDR#9]
Hello. I want to fine-tune this model with my dataset. There is no guide about adding a new dataset to the model. Are there any tips or caution about fine-tuning this model?

**Comment by Chenrj233** [comment]
You can achieve this by converting your dataset to the same format as `train_self_original.txt`, or you need to refer to the implementation of [create_data(), build_dataloader()](https://github.com/Chenrj233/LMEDR/blob/b0db3d3d788c1a0207c56e7b869f69ea2dfef084/train_PersonaChat.py#LL135C5-L139C119) to execute the same processing on the input.

**Comment by bizli0618** [comment]
Thanks!
